[SERVICE]
    Flush 15
    Parsers_File parsers.conf
[INPUT]
    Name tail
    Path /var/lib/docker/containers/*/*.log
    Parser docker
    Tag app.*
    Mem_Buf_Limit 50MB
[INPUT]
    Name tail
    Path /host/var/log/nginx/access.log
    Parser nginx
    Tag nginx.access
[INPUT]
    Name tail
    Path /host/var/log/syslog,/host/var/log/auth.log
    Parser syslog
    Tag os.*